src/main/java/at/mynewjob/domain/Book.java
package at.mynewjob.domain;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;

import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.format.annotation.NumberFormat;
import org.springframework.format.number.NumberFormatter;

/**
 * A book in the library.
 * @author andreas
 */
@Entity
public class Book implements Serializable {

	private static final long serialVersionUID = 1L;
	private static final String CURRENCY_PATTERN = "#,##0.00";

	@Id
	@GeneratedValue
	private Long id;
	
	@Size(min=10, max=17)
	private String isbn;
	
	@Size(min=1, max=255)
	private String title;
	
	@Min(0)
	@Digits(fraction=2, integer=8)
	@NumberFormat(pattern=CURRENCY_PATTERN)
	private BigDecimal price;
	
	Book() {
		// default constructor for Hibernate
	}
	
	public Book(String isbn, String title, BigDecimal price) {
		super();
		this.isbn = isbn;
		this.title = title;
		this.price = price;
	}
	
	public String getFormattedPrice() {
		if (price == null)
			return "";
		return new NumberFormatter(CURRENCY_PATTERN)
			.print(price, LocaleContextHolder.getLocale());
	}
	
	public String getIsbn() {
		return isbn;
	}
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public BigDecimal getPrice() {
		return price;
	}
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@Override
	public String toString() {
		return "Book [id=" + id + ", title=" + title + "]";
	}
	
}

src/main/java/at/mynewjob/controller/BookController.java
package at.mynewjob.controller;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import at.mynewjob.Application;
import at.mynewjob.domain.Book;
import at.mynewjob.repositories.BookRepository;

@Controller
public class BookController {

	private static final Logger log = Logger.getLogger(BookController.class);
	
	@Autowired
	private BookRepository bookRepo;
	
	void setRepo(BookRepository bookRepo) {
		this.bookRepo = bookRepo;
	}
	
	@RequestMapping(value="/books", method=RequestMethod.GET)
	public String showBookList(Integer start, Integer max, Model model) {
		log.info("showing books");
		if (start == null || start < 0)
			start = 0;
		if (max == null || max <= 0)
			max = 10;
		
		int totalCount = bookRepo.count();
		if (start >= totalCount)
			start = Math.max(0, totalCount - max);
		
		List<Book> books = bookRepo.findEntries(start, max);
		
		model.addAttribute("books", books);
		int from = totalCount > 0 ? start+1 : 0;
		model.addAttribute("from", from);
		model.addAttribute("to", start + books.size());
		model.addAttribute("count", totalCount);
		model.addAttribute("max", max);
		
		model.addAttribute("hasBefore", start > 0);
		model.addAttribute("beforeStart", Math.max(0, start - max));
		
		model.addAttribute("hasAfter", start + max < totalCount);
		model.addAttribute("afterStart", start + books.size());
		
		addLoggedInStatus(model);
		
		return "booklist";
	}
	
	private void addLoggedInStatus(Model model) {
		if (! Application.currentUserIsAdmin())
			model.addAttribute("showLogin", true);
		else {
			model.addAttribute("showCreate", true);
			model.addAttribute("showEdit", true);
			model.addAttribute("showDelete", true);
		}
	}

	@RequestMapping(value="/books/create", method=RequestMethod.GET)
	public String showBookCreation(Model model) {
		log.info("book creation");
		model.addAttribute("book", new Book("", "", null));
		model.addAttribute("isCreation", true);
		return "book";
	}
	
	@RequestMapping(value="/books/create", method=RequestMethod.POST)
	public String createBook(@Valid Book book, BindingResult result, Model model) {
		log.info("create book");
		if (result.hasErrors()) {
			model.addAttribute("book", book);
			return "book";
		}
		bookRepo.persist(book);
		return "redirect:/books";
	}
	
	@RequestMapping(value="/books/{id}", method=RequestMethod.GET)
	public String showBook(@PathVariable long id, Model model) {
		log.info("showing book " + id);
		Book book = bookRepo.find(id);
		if (book == null)
			return "redirect:/books";
		model.addAttribute("book", book);
		return "book";
	}
	
	@RequestMapping(value="/books/{id}", method=RequestMethod.POST)
	public String changeBook(@PathVariable long id, @Valid Book book, BindingResult result, Model model) {
		log.info("changing book " + id);
		if (id != book.getId())
			throw new RuntimeException("no book/wrong id");
		if (result.hasErrors()) {
			model.addAttribute("book", book);
			return "book";
		}
		bookRepo.merge(book);
		return "redirect:/books";
	}
	
	@RequestMapping(value="/books/{id}", method=RequestMethod.DELETE)
	public void deleteBook(@PathVariable long id, HttpServletResponse response) throws IOException {
		log.info("deleting book " + id);
		bookRepo.remove(id);
		PrintWriter writer = response.getWriter();
		writer.println("{}");
	}
	
	@RequestMapping(value="/books/insertDemoBooks", method=RequestMethod.GET)
	public void insertDemoBooks(HttpServletResponse response) throws IOException {
		log.info("inserting demo books");
		bookRepo.insertDemoBooks();
		PrintWriter writer = response.getWriter();
		writer.println("done");
	}
}

src/main/webapp/WEB-INF/jsp/book.jsp
<!DOCTYPE html>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html lang="en">

<head>
<title><c:out value="${book.title}"/></title>
<link rel="stylesheet" type="text/css" href="../style.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>

</head>


<body>

<h1>
<c:if test="${isCreation}"><spring:message code="createNewBook"/></c:if>
<c:out value="${book.title}"/>
</h1>

<form:form commandName="book">
<table class="book center">
<tr>
	<td><spring:message code="isbn"/>: </td>
	<td><form:input path="isbn" /></td>
	<td class="error"><form:errors path="isbn" /></td>
</tr>
<tr>
	<td><spring:message code="title"/>: </td>
	<td><form:input path="title" size="50" /></td>
	<td class="error"><form:errors path="title" /></td>
</tr>
<tr>
	<td><spring:message code="price"/>: </td>
	<td><form:input path="price" /></td>
	<td class="error"><form:errors path="price" /></td>
</tr>
<tr>
	<td colspan="3">
		<form:hidden path="id" />
		<spring:message code="save" var="saveText"/>
		<input type="submit" value="${saveText}" class="tableButton" />
		<spring:message code="cancel" var="cancelText"/>
		<input type="button" value="${cancelText}" onclick="javascript:window.history.back()" class="tableButton" />
	</td>
</tr>
</table>
</form:form>

<br/>

</body>

</html>

src/main/webapp/WEB-INF/jsp/booklist.jsp
<!DOCTYPE html >
<%@page contentType="text/html;charset=UTF-8;" pageEncoding="UTF-8"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html lang="en">

<head>

<title>Books</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="_csrf" content="${_csrf.token}"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="style.css">
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
<script>
	var selectedBook = -1;
	function populate() {
		var token = $("meta[name='_csrf']").attr("content");
		$.ajax({
			type: "GET",
			headers: {"X-CSRF-TOKEN" : token},
			url: "books/insertDemoBooks",
		})
		.done(function( msg ) {
			console.log("populated");
			location.reload();
		});
	}
	function askDelete(id) {
		selectedBook = id;
		$("#dlgConfirmDelete").dialog("open")
	}
	function doDelete() {
		var bookToDelete = selectedBook;
		var token = $("meta[name='_csrf']").attr("content");
		$.ajax({
			type: "DELETE",
			headers: {"X-CSRF-TOKEN" : token},
			url: "books/" + bookToDelete,
		})
		.done(function() {
			$("#row" + bookToDelete).hide("slow");
		})
		.fail(function() {
			console.log("deletion failed");
			$("#dlgDeleteError").dialog("open")
		});
	}
	$(function() {
		$("#dlgConfirmDelete").dialog({
			autoOpen: false,
			resizable : false,
			height : 200,
			width : 400,
			modal : true,
			buttons : {
				<spring:message code="delete"/> : function() {
					$(this).dialog("close");
					doDelete();
				},
				<spring:message code="cancel"/> : function() {
					$(this).dialog("close");
				}
			}
		});
	});
	$(function() {
		$("#dlgDeleteError").dialog({autoOpen: false});
	});
</script>
</head>


<body>

<h1><spring:message code="books"/></h1>


<table class="booklist center">
<tr>
	<th><spring:message code="isbn"/></th>
	<th><spring:message code="title"/></th>
	<th><spring:message code="price"/></th>
	<th/>
</tr>
<c:forEach var="book" items="${books}">
	<tr id="row${book.id}">
		<td><c:out value="${book.isbn}"/></td>
		<td>
			<c:if test="${showCreate}">
				<a href="/books/${book.id}"><c:out value="${book.title}"/></a>
			</c:if>
			<c:if test="${not showCreate}"><c:out value="${book.title}"/></c:if>
		</td>
		<td style="text-align:right"><c:out value="${book.formattedPrice} €"/></td>
		<td><c:if test="${showDelete}">
			<button onclick="askDelete(${book.id})">x</button>
		</c:if></td>
	</tr>
</c:forEach>

<tr class="pager"><td colspan="4">
	<c:if test="${not hasBefore}">«</c:if>
	<c:url value="books?start=${beforeStart}&max=${max}" var="link"/>
	<c:if test="${hasBefore}"><a href="${link}">«</a></c:if>
	
	<c:out value="${from}"/> - <c:out value="${to}"/> (<c:out value="${count}"/>)
	
	<c:if test="${not hasAfter}">»</c:if>
	<c:url value="books?start=${afterStart}&max=${max}" var="link"/>
	<c:if test="${hasAfter}"><a href="${link}">»</a></c:if>
</td></tr>
</table>

<br/>

<c:if test="${showLogin}"><a class="taskLink" href="/login">Login</a></c:if>
<c:if test="${showCreate}">
	<a class="taskLink" href="/books/create"><spring:message code="createNewBook"/></a>
</c:if>
<a class="taskLink" href="javascript:populate()"><spring:message code="populate"/></a>


<spring:message code="delete" var="dlgTitle"/>
<div id="dlgConfirmDelete" title="${dlgTitle}">
<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
<spring:message code="deleteQuestion"/></p>
</div>

<spring:message code="deleteErrorTitle" var="dlgErrorTitle"/>
<div id="dlgDeleteError" title="${dlgErrorTitle}">
<p><spring:message code="deleteErrorText"/></p>
</div>

</body>

</html>

src/main/webapp/WEB-INF/jsp/login.jsp
<!DOCTYPE html>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html lang="en">

<head>
<title>Login</title>
<link rel="stylesheet" type="text/css" href="style.css">
</head>


<body>

<h1>Login</h1>

<c:url value="/login" var="loginProcessingUrl" />
<form action="${loginProcessingUrl}" method="post">
	<fieldset class="center" style="width:500px">
		<legend><spring:message code="pleaseLogin"/></legend>
		<!-- use param.error assuming FormLoginConfigurer#failureUrl contains the query parameter error -->
		<c:if test="${param.error != null}">
			<div class="error"><spring:message code="loginFailed"/></div>
		</c:if>
		<!-- the configured LogoutConfigurer#logoutSuccessUrl is /login?logout and contains the query param logout -->
		<c:if test="${param.logout != null}">
			<div><spring:message code="loggedOut"/></div>
		</c:if>
		<p>
			<label for="username"><spring:message code="userName"/> (admin):</label>
			<input type="text" id="username" name="username" />
		</p>
		<p>
			<label for="password"><spring:message code="password"/> (admin):</label> 
			<input type="password" id="password" name="password" />
		</p>
		<div>
			<input type="hidden" id="_csrf" name="_csrf" value="${_csrf.token}" />
			<button type="submit">Log in</button>
			<spring:message code="cancel" var="cancelText"/>
		<input type="button" value="${cancelText}" onclick="javascript:window.history.back()" />
		</div>
	</fieldset>
</form>

</body>

</html>